apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: db-imgur
  name: db-imgur
  namespace: leagueshare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi