apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules-keycloak
  namespace: leagueshare
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: keycloak
            port:
              number: 8080
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules-imgur
  namespace: leagueshare
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /imgur
        pathType: Prefix
        backend:
          service:
            name: imgur-service
            port:
              number: 8091  
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-rules-user
  namespace: leagueshare
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: user-service
            port:
              number: 8092 