apiVersion: v1
data:
  X-Forwarded-Proto: $scheme
  X-Forwarded-For: $proxy_add_x_forwarded_for
  X-Forwarded-Port: $server_port
  proxy_pass: "http://keycloak:8080"
kind: ConfigMap
metadata:
  name: custom-headers
  namespace: ingress-nginx